apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aniket-app-deploy
  name: aniket-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aniket-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aniket-app-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}